[package]
name = "net2"
version = "0.2.23"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/net2-rs"
homepage = "https://github.com/rust-lang-nursery/net2-rs"
documentation = "https://doc.rust-lang.org/net2-rs/"
description = """
Extensions to the standard library's networking types as proposed in RFC 1158.
"""

[dependencies]
libc = "0.2.6"
cfg-if = "0.1"

[target.'cfg(windows)'.dependencies]
ws2_32-sys = "0.2"
winapi = "0.2"
kernel32-sys = "0.2"

[features]
nightly = []
duration = []
default = ["duration"]
